# PostgreSQL. Versions 9.3 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: postgres
  # database: internet_shop
  # username: db_user
  # password: db_pass

development:
  <<: *default
  # database: internet_shop
  # host: postgres
  # username: db_user
  # password: db_pass

test:
  <<: *default
  database: main_test